import { WorkflowTemplate } from '@/types/workflow';

export const commonWorkflows: WorkflowTemplate[] = [
    {
        id: 'merge-compress',
        name: 'Merge & Compress',
        description: 'Merge multiple PDFs and compress the result for smaller file size',
        category: 'common',
        nodes: [
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'merge-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'document-prep',
        name: 'Document Preparation',
        description: 'Merge PDFs, add page numbers, and add header/footer',
        category: 'common',
        nodes: [
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 400, y: 150 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'header-footer-1',
                type: 'toolNode',
                position: { x: 700, y: 150 },
                data: {
                    toolId: 'header-footer',
                    label: 'Add Header/Footer',
                    icon: 'pilcrow',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'merge-1',
                target: 'page-numbers-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'page-numbers-1',
                target: 'header-footer-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'split-and-watermark',
        name: 'Split & Watermark',
        description: 'Split PDF into pages and add watermark to each',
        category: 'common',
        nodes: [
            {
                id: 'split-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'split-pdf',
                    label: 'Split PDF',
                    icon: 'scissors',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'split-1',
                target: 'watermark-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'rotate-and-number',
        name: 'Rotate & Add Page Numbers',
        description: 'Rotate PDF pages and add page numbers',
        category: 'common',
        nodes: [
            {
                id: 'rotate-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'rotate-pdf',
                    label: 'Rotate PDF',
                    icon: 'rotate-cw',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'rotate-1',
                target: 'page-numbers-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'print-ready',
        name: 'Print Ready Document',
        description: 'Prepare PDF for printing with page numbers and flatten',
        category: 'common',
        nodes: [
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'flatten-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'flatten-pdf',
                    label: 'Flatten PDF',
                    icon: 'layers',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'page-numbers-1',
                target: 'flatten-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'extract-and-merge',
        name: 'Extract & Merge Pages',
        description: 'Extract specific pages and merge them into a new document',
        category: 'common',
        nodes: [
            {
                id: 'extract-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'extract-pages',
                    label: 'Extract Pages',
                    icon: 'copy',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'extract-1',
                target: 'merge-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'crop-and-resize',
        name: 'Crop & Resize Pages',
        description: 'Crop PDF pages and adjust page dimensions',
        category: 'common',
        nodes: [
            {
                id: 'crop-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'crop-pdf',
                    label: 'Crop PDF',
                    icon: 'crop',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'resize-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'fix-page-size',
                    label: 'Fix Page Size',
                    icon: 'ruler',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'crop-1',
                target: 'resize-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'batch-watermark',
        name: 'Batch Watermark',
        description: 'Add watermark to multiple PDF files at once',
        category: 'common',
        nodes: [
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                    settings: {
                        text: 'WATERMARK',
                        opacity: 0.3,
                    },
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'report-assembly',
        name: 'Report Assembly',
        description: 'Merge documents, add page numbers, header/footer and table of contents',
        category: 'common',
        nodes: [
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 400, y: 150 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'header-footer-1',
                type: 'toolNode',
                position: { x: 700, y: 150 },
                data: {
                    toolId: 'header-footer',
                    label: 'Add Header/Footer',
                    icon: 'pilcrow',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'toc-1',
                type: 'toolNode',
                position: { x: 1000, y: 150 },
                data: {
                    toolId: 'table-of-contents',
                    label: 'Add Table of Contents',
                    icon: 'list',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'merge-1',
                target: 'page-numbers-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'page-numbers-1',
                target: 'header-footer-1',
                isValid: true,
            },
            {
                id: 'edge-3',
                source: 'header-footer-1',
                target: 'toc-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'invoice-processing',
        name: 'Invoice Processing',
        description: 'Extract pages, add watermark, and compress for email',
        category: 'common',
        nodes: [
            {
                id: 'extract-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'extract-pages',
                    label: 'Extract Pages',
                    icon: 'copy',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 700, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'extract-1',
                target: 'watermark-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'watermark-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];
