import { WorkflowTemplate } from '@/types/workflow';

export const conversionWorkflows: WorkflowTemplate[] = [
    {
        id: 'images-to-pdf-watermark',
        name: 'Images to Watermarked PDF',
        description: 'Convert images to PDF and add a custom watermark',
        category: 'conversion',
        nodes: [
            {
                id: 'image-to-pdf-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'image-to-pdf',
                    label: 'Image to PDF',
                    icon: 'images',
                    category: 'convert-to-pdf',
                    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.bmp', '.tiff', '.tif', '.svg', '.heic'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'image-to-pdf-1',
                target: 'watermark-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'pdf-to-images-compress',
        name: 'PDF to Compressed Images',
        description: 'Convert PDF pages to JPG images',
        category: 'conversion',
        nodes: [
            {
                id: 'pdf-to-jpg-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'pdf-to-jpg',
                    label: 'PDF to JPG',
                    icon: 'file-image',
                    category: 'convert-from-pdf',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'jpg',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'office-to-pdf-merge',
        name: 'Office Files to Single PDF',
        description: 'Convert Word documents to PDF and merge them',
        category: 'conversion',
        nodes: [
            {
                id: 'word-to-pdf-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'word-to-pdf',
                    label: 'Word to PDF',
                    icon: 'file-text',
                    category: 'convert-to-pdf',
                    acceptedFormats: ['.doc', '.docx'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'word-to-pdf-1',
                target: 'merge-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'pdf-to-docx-cleanup',
        name: 'PDF to Editable Document',
        description: 'Convert PDF to Word document for editing',
        category: 'conversion',
        nodes: [
            {
                id: 'pdf-to-docx-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'pdf-to-docx',
                    label: 'PDF to Word',
                    icon: 'file-text',
                    category: 'convert-from-pdf',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'docx',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'pdf-to-presentation',
        name: 'PDF to PowerPoint',
        description: 'Convert PDF to editable PowerPoint presentation',
        category: 'conversion',
        nodes: [
            {
                id: 'pdf-to-pptx-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'pdf-to-pptx',
                    label: 'PDF to PowerPoint',
                    icon: 'presentation',
                    category: 'convert-from-pdf',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pptx',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'ebook-convert',
        name: 'eBook to PDF',
        description: 'Convert EPUB eBooks to PDF format',
        category: 'conversion',
        nodes: [
            {
                id: 'epub-to-pdf-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'epub-to-pdf',
                    label: 'EPUB to PDF',
                    icon: 'book-open',
                    category: 'convert-to-pdf',
                    acceptedFormats: ['.epub'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'epub-to-pdf-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'photo-album',
        name: 'Photo Album Creator',
        description: 'Convert images to PDF with page numbers',
        category: 'conversion',
        nodes: [
            {
                id: 'image-to-pdf-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'image-to-pdf',
                    label: 'Image to PDF',
                    icon: 'images',
                    category: 'convert-to-pdf',
                    acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.bmp', '.tiff', '.tif', '.svg', '.heic'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'page-numbers-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'page-numbers',
                    label: 'Add Page Numbers',
                    icon: 'list-ordered',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'image-to-pdf-1',
                target: 'page-numbers-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];
