import { WorkflowTemplate } from '@/types/workflow';

export const optimizationWorkflows: WorkflowTemplate[] = [
    {
        id: 'optimize-for-web',
        name: 'Optimize for Web',
        description: 'Compress and linearize PDF for fast web viewing',
        category: 'optimization',
        nodes: [
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'linearize-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'linearize-pdf',
                    label: 'Linearize PDF',
                    icon: 'zap-off',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'compress-1',
                target: 'linearize-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'grayscale-compress',
        name: 'Grayscale & Compress',
        description: 'Convert to grayscale and compress for smaller size',
        category: 'optimization',
        nodes: [
            {
                id: 'grayscale-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'pdf-to-greyscale',
                    label: 'Convert to Grayscale',
                    icon: 'palette',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'grayscale-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'comprehensive-optimization',
        name: 'Full Document Optimization',
        description: 'Compress, flatten, and linearize for optimal performance',
        category: 'optimization',
        nodes: [
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'flatten-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'flatten-pdf',
                    label: 'Flatten PDF',
                    icon: 'layers',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'linearize-1',
                type: 'toolNode',
                position: { x: 700, y: 200 },
                data: {
                    toolId: 'linearize-pdf',
                    label: 'Linearize PDF',
                    icon: 'zap-off',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'compress-1',
                target: 'flatten-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'flatten-1',
                target: 'linearize-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'archive-prep',
        name: 'Archive Preparation',
        description: 'Remove metadata, flatten, and compress for long-term storage',
        category: 'optimization',
        nodes: [
            {
                id: 'remove-metadata-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'remove-metadata',
                    label: 'Remove Metadata',
                    icon: 'file-minus',
                    category: 'security-privacy',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'flatten-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'flatten-pdf',
                    label: 'Flatten PDF',
                    icon: 'layers',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'compress-1',
                type: 'toolNode',
                position: { x: 700, y: 200 },
                data: {
                    toolId: 'compress-pdf',
                    label: 'Compress PDF',
                    icon: 'zap',
                    category: 'optimize-repair',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'remove-metadata-1',
                target: 'flatten-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'flatten-1',
                target: 'compress-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];
