import { WorkflowTemplate } from '@/types/workflow';

export const securityWorkflows: WorkflowTemplate[] = [
    {
        id: 'secure-pdf',
        name: 'Create Secure PDF',
        description: 'Merge PDFs, add watermark, and encrypt with password',
        category: 'security',
        nodes: [
            {
                id: 'merge-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'merge-pdf',
                    label: 'Merge PDF',
                    icon: 'combine',
                    category: 'organize-manage',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
            {
                id: 'encrypt-1',
                type: 'toolNode',
                position: { x: 700, y: 200 },
                data: {
                    toolId: 'encrypt-pdf',
                    label: 'Encrypt PDF',
                    icon: 'lock',
                    category: 'security-privacy',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'merge-1',
                target: 'watermark-1',
                isValid: true,
            },
            {
                id: 'edge-2',
                source: 'watermark-1',
                target: 'encrypt-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'confidential-document',
        name: 'Confidential Document',
        description: 'Add confidential watermark and encrypt PDF',
        category: 'security',
        nodes: [
            {
                id: 'watermark-1',
                type: 'toolNode',
                position: { x: 100, y: 200 },
                data: {
                    toolId: 'add-watermark',
                    label: 'Add Watermark',
                    icon: 'droplets',
                    category: 'edit-annotate',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                    settings: {
                        text: 'CONFIDENTIAL',
                        opacity: 0.3,
                    },
                },
            },
            {
                id: 'encrypt-1',
                type: 'toolNode',
                position: { x: 400, y: 200 },
                data: {
                    toolId: 'encrypt-pdf',
                    label: 'Encrypt PDF',
                    icon: 'lock',
                    category: 'security-privacy',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [
            {
                id: 'edge-1',
                source: 'watermark-1',
                target: 'encrypt-1',
                isValid: true,
            },
        ],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
    {
        id: 'unlock-and-edit',
        name: 'Unlock & Edit PDF',
        description: 'Decrypt protected PDF for editing',
        category: 'security',
        nodes: [
            {
                id: 'decrypt-1',
                type: 'toolNode',
                position: { x: 250, y: 200 },
                data: {
                    toolId: 'decrypt-pdf',
                    label: 'Decrypt PDF',
                    icon: 'unlock',
                    category: 'security-privacy',
                    acceptedFormats: ['.pdf'],
                    outputFormat: 'pdf',
                    status: 'idle',
                    progress: 0,
                },
            },
        ],
        edges: [],
        createdAt: '2024-01-01T00:00:00Z',
        updatedAt: '2024-01-01T00:00:00Z',
    },
];
