import { Tool } from '@/types/tool';
import { DEFAULT_MAX_FILE_SIZE, LARGE_FILE_SIZE } from './constants';

export const convertToPdfTools: Tool[] = [
    {
        id: 'jpg-to-pdf',
        slug: 'jpg-to-pdf',
        icon: 'image-up',
        category: 'convert-to-pdf',
        acceptedFormats: ['.jpg', '.jpeg'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 100,
        features: ['multiple-images', 'page-order', 'page-size'],
        relatedTools: ['png-to-pdf', 'image-to-pdf', 'pdf-to-jpg'],
    },
    {
        id: 'image-to-pdf',
        slug: 'image-to-pdf',
        icon: 'images',
        category: 'convert-to-pdf',
        acceptedFormats: ['.jpg', '.jpeg', '.png', '.webp', '.bmp', '.tiff', '.tif', '.svg', '.heic'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 100,
        features: ['multiple-formats', 'page-order', 'page-size', 'orientation'],
        relatedTools: ['jpg-to-pdf', 'png-to-pdf', 'pdf-to-jpg'],
    },
    {
        id: 'png-to-pdf',
        slug: 'png-to-pdf',
        icon: 'image-up',
        category: 'convert-to-pdf',
        acceptedFormats: ['.png'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 100,
        features: ['multiple-images', 'transparency', 'page-size'],
        relatedTools: ['jpg-to-pdf', 'image-to-pdf', 'pdf-to-png'],
    },
    {
        id: 'webp-to-pdf',
        slug: 'webp-to-pdf',
        icon: 'image-up',
        category: 'convert-to-pdf',
        acceptedFormats: ['.webp'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 100,
        features: ['multiple-images', 'page-size', 'quality'],
        relatedTools: ['jpg-to-pdf', 'png-to-pdf', 'pdf-to-webp'],
    },
    {
        id: 'svg-to-pdf',
        slug: 'svg-to-pdf',
        icon: 'pen-tool',
        category: 'convert-to-pdf',
        acceptedFormats: ['.svg'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 100,
        features: ['vector-quality', 'multiple-files', 'page-size'],
        relatedTools: ['image-to-pdf', 'png-to-pdf', 'jpg-to-pdf'],
    },
    {
        id: 'bmp-to-pdf',
        slug: 'bmp-to-pdf',
        icon: 'image',
        category: 'convert-to-pdf',
        acceptedFormats: ['.bmp'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 100,
        features: ['multiple-images', 'page-size', 'compression'],
        relatedTools: ['jpg-to-pdf', 'png-to-pdf', 'pdf-to-bmp'],
    },
    {
        id: 'heic-to-pdf',
        slug: 'heic-to-pdf',
        icon: 'smartphone',
        category: 'convert-to-pdf',
        acceptedFormats: ['.heic', '.heif'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 100,
        features: ['iphone-photos', 'multiple-images', 'page-size'],
        relatedTools: ['jpg-to-pdf', 'image-to-pdf', 'png-to-pdf'],
    },
    {
        id: 'tiff-to-pdf',
        slug: 'tiff-to-pdf',
        icon: 'layers',
        category: 'convert-to-pdf',
        acceptedFormats: ['.tiff', '.tif'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 100,
        features: ['multi-page-tiff', 'high-quality', 'page-size'],
        relatedTools: ['image-to-pdf', 'pdf-to-tiff', 'jpg-to-pdf'],
    },
    {
        id: 'txt-to-pdf',
        slug: 'txt-to-pdf',
        icon: 'file-pen',
        category: 'convert-to-pdf',
        acceptedFormats: ['.txt'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['font-selection', 'page-size', 'margins'],
        relatedTools: ['json-to-pdf', 'image-to-pdf', 'merge-pdf'],
    },
    {
        id: 'json-to-pdf',
        slug: 'json-to-pdf',
        icon: 'file-code',
        category: 'convert-to-pdf',
        acceptedFormats: ['.json'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['formatted-output', 'syntax-highlighting', 'page-size'],
        relatedTools: ['pdf-to-json', 'txt-to-pdf', 'merge-pdf'],
    },
    {
        id: 'psd-to-pdf',
        slug: 'psd-to-pdf',
        icon: 'image',
        category: 'convert-to-pdf',
        acceptedFormats: ['.psd', '.psb'],
        outputFormat: 'pdf',
        maxFileSize: LARGE_FILE_SIZE,
        maxFiles: 100,
        features: ['multiple-files', 'psd-layers', 'page-size'],
        relatedTools: ['image-to-pdf', 'jpg-to-pdf', 'png-to-pdf'],
    },
    {
        id: 'word-to-pdf',
        slug: 'word-to-pdf',
        icon: 'file-text',
        category: 'convert-to-pdf',
        acceptedFormats: ['.docx', '.doc'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-layout', 'preserve-formatting', 'extract-text'],
        relatedTools: ['pdf-to-docx', 'txt-to-pdf', 'excel-to-pdf'],
    },
    {
        id: 'excel-to-pdf',
        slug: 'excel-to-pdf',
        icon: 'file-spreadsheet',
        category: 'convert-to-pdf',
        acceptedFormats: ['.xlsx', '.xls'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-tables', 'multiple-sheets', 'page-layout'],
        relatedTools: ['pdf-to-excel', 'word-to-pdf', 'pptx-to-pdf'],
    },
    {
        id: 'pptx-to-pdf',
        slug: 'pptx-to-pdf',
        icon: 'presentation',
        category: 'convert-to-pdf',
        acceptedFormats: ['.pptx', '.ppt'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-slides', 'preserve-layout', 'high-quality'],
        relatedTools: ['pdf-to-pptx', 'word-to-pdf', 'excel-to-pdf'],
    },
    {
        id: 'xps-to-pdf',
        slug: 'xps-to-pdf',
        icon: 'file-box',
        category: 'convert-to-pdf',
        acceptedFormats: ['.xps'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-layout', 'high-fidelity', 'vector-graphics'],
        relatedTools: ['word-to-pdf', 'image-to-pdf', 'merge-pdf'],
    },
    {
        id: 'rtf-to-pdf',
        slug: 'rtf-to-pdf',
        icon: 'file-type',
        category: 'convert-to-pdf',
        acceptedFormats: ['.rtf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-formatting', 'extract-text', 'page-size'],
        relatedTools: ['word-to-pdf', 'txt-to-pdf', 'merge-pdf'],
    },
    {
        id: 'epub-to-pdf',
        slug: 'epub-to-pdf',
        icon: 'book-open',
        category: 'convert-to-pdf',
        acceptedFormats: ['.epub'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-formatting', 'preserve-images', 'chapter-structure'],
        relatedTools: ['word-to-pdf', 'txt-to-pdf', 'html-to-pdf'],
    },
    {
        id: 'mobi-to-pdf',
        slug: 'mobi-to-pdf',
        icon: 'book-marked',
        category: 'convert-to-pdf',
        acceptedFormats: ['.mobi', '.azw', '.azw3'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-formatting', 'preserve-images', 'chapter-structure'],
        relatedTools: ['epub-to-pdf', 'fb2-to-pdf', 'txt-to-pdf'],
    },
    {
        id: 'djvu-to-pdf',
        slug: 'djvu-to-pdf',
        icon: 'file-scan',
        category: 'convert-to-pdf',
        acceptedFormats: ['.djvu', '.djv'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-formatting', 'dpi-setting', 'quality-setting'],
        relatedTools: ['image-to-pdf', 'scan-to-pdf', 'ocr-pdf'],
    },
    {
        id: 'fb2-to-pdf',
        slug: 'fb2-to-pdf',
        icon: 'book-text',
        category: 'convert-to-pdf',
        acceptedFormats: ['.fb2', '.fb2.zip'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 20,
        features: ['preserve-formatting', 'preserve-images', 'chapter-structure', 'multiple-files'],
        relatedTools: ['epub-to-pdf', 'mobi-to-pdf', 'txt-to-pdf'],
    },
    {
        id: 'markdown-to-pdf',
        slug: 'markdown-to-pdf',
        icon: 'file-type',
        category: 'convert-to-pdf',
        acceptedFormats: ['.md', '.markdown', '.txt'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['commonmark', 'gfm', 'code-highlighting', 'themes', 'tables'],
        relatedTools: ['text-to-pdf', 'html-to-pdf', 'word-to-pdf'],
    },
    {
        id: 'email-to-pdf',
        slug: 'email-to-pdf',
        icon: 'mail',
        category: 'convert-to-pdf',
        acceptedFormats: ['.eml', '.msg'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['inline-images', 'attachments', 'cc-bcc', 'date-formatting'],
        relatedTools: ['html-to-pdf', 'word-to-pdf', 'attachments'],
    },
    {
        id: 'cbz-to-pdf',
        slug: 'cbz-to-pdf',
        icon: 'book-image',
        category: 'convert-to-pdf',
        acceptedFormats: ['.cbz', '.zip'],
        outputFormat: 'pdf',
        maxFileSize: LARGE_FILE_SIZE,
        maxFiles: 10,
        features: ['comic-archive', 'image-extraction', 'page-order', 'page-sizes'],
        relatedTools: ['jpg-to-pdf', 'image-to-pdf', 'epub-to-pdf'],
    },
];
