import { Tool } from '@/types/tool';
import { DEFAULT_MAX_FILE_SIZE } from './constants';

export const convertFromPdfTools: Tool[] = [
    {
        id: 'pdf-to-jpg',
        slug: 'pdf-to-jpg',
        icon: 'file-image',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'jpg',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['all-pages', 'selected-pages', 'quality-setting', 'dpi-setting'],
        relatedTools: ['pdf-to-png', 'jpg-to-pdf', 'pdf-to-webp'],
    },
    {
        id: 'pdf-to-png',
        slug: 'pdf-to-png',
        icon: 'file-image',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'png',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['all-pages', 'selected-pages', 'transparency', 'dpi-setting'],
        relatedTools: ['pdf-to-jpg', 'png-to-pdf', 'pdf-to-webp'],
    },
    {
        id: 'pdf-to-webp',
        slug: 'pdf-to-webp',
        icon: 'file-image',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'webp',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['all-pages', 'selected-pages', 'quality-setting', 'compression'],
        relatedTools: ['pdf-to-jpg', 'pdf-to-png', 'webp-to-pdf'],
    },
    {
        id: 'pdf-to-bmp',
        slug: 'pdf-to-bmp',
        icon: 'file-image',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'bmp',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['all-pages', 'selected-pages', 'dpi-setting'],
        relatedTools: ['pdf-to-jpg', 'pdf-to-png', 'bmp-to-pdf'],
    },
    {
        id: 'pdf-to-tiff',
        slug: 'pdf-to-tiff',
        icon: 'file-image',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'tiff',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['all-pages', 'multi-page-tiff', 'dpi-setting', 'compression'],
        relatedTools: ['pdf-to-jpg', 'tiff-to-pdf', 'pdf-to-png'],
    },
    {
        id: 'pdf-to-svg',
        slug: 'pdf-to-svg',
        icon: 'file-code',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'svg',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['vector-output', 'scalable-quality', 'page-preview', 'individual-export'],
        relatedTools: ['pdf-to-png', 'svg-to-pdf', 'pdf-to-jpg'],
    },
    {
        id: 'pdf-to-greyscale',
        slug: 'pdf-to-greyscale',
        icon: 'palette',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['convert-colors', 'preserve-text', 'all-pages'],
        relatedTools: ['invert-colors', 'compress-pdf', 'background-color'],
    },
    {
        id: 'pdf-to-json',
        slug: 'pdf-to-json',
        icon: 'file-code',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'json',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['extract-text', 'extract-metadata', 'structured-output'],
        relatedTools: ['json-to-pdf', 'view-metadata', 'ocr-pdf'],
    },
    {
        id: 'pdf-to-docx',
        slug: 'pdf-to-docx',
        icon: 'file-text',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'docx',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-layout', 'editable-word', 'extract-images'],
        relatedTools: ['pdf-to-json', 'ocr-pdf', 'edit-pdf'],
    },
    {
        id: 'pdf-to-pptx',
        slug: 'pdf-to-pptx',
        icon: 'presentation',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pptx',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['preserve-layout', 'editable-slides', 'high-quality-images'],
        relatedTools: ['pdf-to-docx', 'pdf-to-excel', 'pdf-to-jpg'],
    },
    {
        id: 'pdf-to-excel',
        slug: 'pdf-to-excel',
        icon: 'table',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'xlsx',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['extract-tables', 'multiple-sheets', 'preserve-data'],
        relatedTools: ['pdf-to-json', 'pdf-to-docx', 'ocr-pdf'],
    },
    {
        id: 'pdf-to-markdown',
        slug: 'pdf-to-markdown',
        icon: 'file-code-2',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'md',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['extract-text', 'preserve-headings', 'detect-lists', 'page-range'],
        relatedTools: ['pdf-to-json', 'pdf-to-docx', 'ocr-pdf'],
    },
    {
        id: 'extract-images',
        slug: 'extract-images',
        icon: 'image-down',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'zip',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 20,
        features: ['extract-all-images', 'filter-small', 'download-zip', 'batch-extract'],
        relatedTools: ['pdf-to-jpg', 'pdf-to-png', 'extract-attachments'],
    },
    {
        id: 'rasterize-pdf',
        slug: 'rasterize-pdf',
        icon: 'grid-2x2',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'image',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['dpi-control', 'png-jpeg-webp', 'page-range', 'batch-export'],
        relatedTools: ['pdf-to-jpg', 'pdf-to-png', 'extract-images'],
    },
    {
        id: 'extract-tables',
        slug: 'extract-tables',
        icon: 'table',
        category: 'convert-from-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'data',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['json-export', 'markdown-export', 'csv-export', 'table-detection'],
        relatedTools: ['pdf-to-excel', 'pdf-to-json', 'ocr'],
    },
];
