import { Tool } from '@/types/tool';
import { DEFAULT_MAX_FILE_SIZE } from './constants';

export const editAnnotateTools: Tool[] = [
    {
        id: 'edit-pdf',
        slug: 'edit-pdf',
        icon: 'pocket-knife',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['edit-text', 'annotate', 'highlight', 'redact', 'comment', 'shapes', 'images', 'search'],
        relatedTools: ['sign-pdf', 'add-watermark', 'form-filler'],
    },
    {
        id: 'sign-pdf',
        slug: 'sign-pdf',
        icon: 'pen-tool',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['draw-signature', 'type-signature', 'upload-signature', 'multiple-signatures'],
        relatedTools: ['edit-pdf', 'form-filler', 'add-stamps'],
    },
    {
        id: 'crop-pdf',
        slug: 'crop-pdf',
        icon: 'crop',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['trim-margins', 'custom-crop', 'all-pages'],
        relatedTools: ['edit-pdf', 'fix-page-size', 'page-dimensions'],
    },
    {
        id: 'bookmark',
        slug: 'bookmark',
        icon: 'bookmark',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['add-bookmarks', 'edit-bookmarks', 'import-bookmarks', 'delete-bookmarks', 'extract-bookmarks'],
        relatedTools: ['table-of-contents', 'edit-pdf', 'edit-metadata'],
    },
    {
        id: 'table-of-contents',
        slug: 'table-of-contents',
        icon: 'list',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['generate-toc', 'from-bookmarks', 'custom-style'],
        relatedTools: ['bookmark', 'page-numbers', 'header-footer'],
    },
    {
        id: 'page-numbers',
        slug: 'page-numbers',
        icon: 'list-ordered',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['custom-position', 'custom-format', 'start-number', 'skip-pages'],
        relatedTools: ['header-footer', 'add-watermark', 'table-of-contents'],
    },
    {
        id: 'add-watermark',
        slug: 'add-watermark',
        icon: 'droplets',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['text-watermark', 'image-watermark', 'position', 'opacity', 'rotation'],
        relatedTools: ['header-footer', 'page-numbers', 'add-stamps'],
    },
    {
        id: 'header-footer',
        slug: 'header-footer',
        icon: 'pilcrow',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['custom-text', 'page-numbers', 'date', 'position'],
        relatedTools: ['page-numbers', 'add-watermark', 'table-of-contents'],
    },
    {
        id: 'invert-colors',
        slug: 'invert-colors',
        icon: 'contrast',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['dark-mode', 'invert-all', 'preserve-images'],
        relatedTools: ['background-color', 'text-color', 'pdf-to-greyscale'],
    },
    {
        id: 'background-color',
        slug: 'background-color',
        icon: 'palette',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['custom-color', 'all-pages', 'selected-pages'],
        relatedTools: ['invert-colors', 'text-color', 'add-watermark'],
    },
    {
        id: 'text-color',
        slug: 'text-color',
        icon: 'type',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['change-text-color', 'all-text', 'selected-text'],
        relatedTools: ['background-color', 'invert-colors', 'edit-pdf'],
    },
    {
        id: 'add-stamps',
        slug: 'add-stamps',
        icon: 'stamp',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['image-stamps', 'preset-stamps', 'custom-position'],
        relatedTools: ['sign-pdf', 'add-watermark', 'edit-pdf'],
    },
    {
        id: 'remove-annotations',
        slug: 'remove-annotations',
        icon: 'eraser',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['remove-comments', 'remove-highlights', 'remove-links', 'selective-removal'],
        relatedTools: ['edit-pdf', 'flatten-pdf', 'sanitize-pdf'],
    },
    {
        id: 'form-filler',
        slug: 'form-filler',
        icon: 'square-pen',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['fill-forms', 'xfa-support', 'save-data', 'flatten-after'],
        relatedTools: ['form-creator', 'sign-pdf', 'edit-pdf'],
    },
    {
        id: 'form-creator',
        slug: 'form-creator',
        icon: 'file-input',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['text-fields', 'checkboxes', 'dropdowns', 'drag-drop'],
        relatedTools: ['form-filler', 'edit-pdf', 'sign-pdf'],
    },
    {
        id: 'remove-blank-pages',
        slug: 'remove-blank-pages',
        icon: 'file-minus-2',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['auto-detect', 'threshold-setting', 'preview'],
        relatedTools: ['delete-pages', 'organize-pdf', 'compress-pdf'],
    },
    {
        id: 'pdf-reader',
        slug: 'pdf-reader',
        icon: 'book-open',
        category: 'edit-annotate',
        acceptedFormats: ['.pdf'],
        outputFormat: 'view',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['page-navigation', 'zoom', 'rotate', 'fullscreen', 'print', 'download'],
        relatedTools: ['sign-pdf', 'annotate-pdf'],
    },
];
