import { Tool } from '@/types/tool';
import { DEFAULT_MAX_FILE_SIZE, LARGE_FILE_SIZE } from './constants';

export const organizeManageTools: Tool[] = [
    {
        id: 'pdf-multi-tool',
        slug: 'pdf-multi-tool',
        icon: 'pencil-ruler',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: LARGE_FILE_SIZE,
        maxFiles: 10,
        features: ['merge', 'split', 'organize', 'delete', 'rotate', 'add-blank', 'extract', 'duplicate'],
        relatedTools: ['merge-pdf', 'split-pdf', 'organize-pdf'],
    },
    {
        id: 'merge-pdf',
        slug: 'merge-pdf',
        icon: 'combine',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: LARGE_FILE_SIZE,
        maxFiles: 100,
        features: ['combine-multiple', 'preserve-bookmarks', 'reorder'],
        relatedTools: ['split-pdf', 'organize-pdf', 'alternate-merge'],
    },
    {
        id: 'split-pdf',
        slug: 'split-pdf',
        icon: 'scissors',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['page-range', 'multiple-outputs', 'extract-pages'],
        relatedTools: ['merge-pdf', 'extract-pages', 'delete-pages'],
    },
    {
        id: 'extract-pages',
        slug: 'extract-pages',
        icon: 'ungroup',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['select-pages', 'multiple-outputs', 'page-range'],
        relatedTools: ['split-pdf', 'delete-pages', 'organize-pdf'],
    },
    {
        id: 'organize-pdf',
        slug: 'organize-pdf',
        icon: 'files',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['reorder-pages', 'duplicate-pages', 'delete-pages', 'drag-drop'],
        relatedTools: ['merge-pdf', 'extract-pages', 'delete-pages'],
    },
    {
        id: 'delete-pages',
        slug: 'delete-pages',
        icon: 'trash-2',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['select-pages', 'preview', 'batch-delete'],
        relatedTools: ['extract-pages', 'organize-pdf', 'split-pdf'],
    },
    {
        id: 'ocr-pdf',
        slug: 'ocr-pdf',
        icon: 'scan-text',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['text-recognition', 'searchable-pdf', 'multiple-languages'],
        relatedTools: ['edit-pdf', 'pdf-to-json', 'compress-pdf'],
    },
    {
        id: 'alternate-merge',
        slug: 'alternate-merge',
        icon: 'shuffle',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: LARGE_FILE_SIZE,
        maxFiles: 10,
        features: ['alternate-pages', 'preserve-bookmarks', 'custom-order'],
        relatedTools: ['merge-pdf', 'organize-pdf', 'split-pdf'],
    },
    {
        id: 'add-attachments',
        slug: 'add-attachments',
        icon: 'paperclip',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['embed-files', 'multiple-attachments', 'any-format'],
        relatedTools: ['extract-attachments', 'edit-attachments', 'edit-metadata'],
    },
    {
        id: 'extract-attachments',
        slug: 'extract-attachments',
        icon: 'download',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'zip',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['extract-all', 'zip-output', 'batch-extract'],
        relatedTools: ['add-attachments', 'edit-attachments', 'pdf-to-zip'],
    },
    {
        id: 'edit-attachments',
        slug: 'edit-attachments',
        icon: 'file-edit',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['view-attachments', 'remove-attachments', 'rename-attachments'],
        relatedTools: ['add-attachments', 'extract-attachments', 'edit-metadata'],
    },
    {
        id: 'divide-pages',
        slug: 'divide-pages',
        icon: 'table-columns-split',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['horizontal-split', 'vertical-split', 'custom-divisions'],
        relatedTools: ['split-pdf', 'n-up-pdf', 'posterize-pdf'],
    },
    {
        id: 'add-blank-page',
        slug: 'add-blank-page',
        icon: 'file-plus-2',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['insert-position', 'page-size', 'multiple-pages'],
        relatedTools: ['organize-pdf', 'delete-pages', 'merge-pdf'],
    },
    {
        id: 'reverse-pages',
        slug: 'reverse-pages',
        icon: 'arrow-down-z-a',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['reverse-order', 'batch-process'],
        relatedTools: ['organize-pdf', 'rotate-pdf', 'split-pdf'],
    },
    {
        id: 'rotate-custom',
        slug: 'rotate-custom',
        icon: 'refresh-ccw',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['custom-angle', 'selected-pages', 'preview'],
        relatedTools: ['rotate-pdf', 'organize-pdf', 'fix-page-size'],
    },
    {
        id: 'rotate-pdf',
        slug: 'rotate-pdf',
        icon: 'rotate-cw',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['90-degree', '180-degree', '270-degree', 'selected-pages'],
        relatedTools: ['organize-pdf', 'crop-pdf', 'fix-page-size'],
    },
    {
        id: 'n-up-pdf',
        slug: 'n-up-pdf',
        icon: 'layout-grid',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['2-up', '4-up', '6-up', '9-up', 'custom-layout'],
        relatedTools: ['divide-pages', 'posterize-pdf', 'combine-single-page', 'grid-combine'],
    },
    {
        id: 'grid-combine',
        slug: 'grid-combine',
        icon: 'layout-dashboard',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 100,
        features: ['combine-multiple-files', 'grid-layout', 'custom-spacing'],
        relatedTools: ['n-up-pdf', 'merge-pdf', 'combine-single-page'],
    },
    {
        id: 'combine-single-page',
        slug: 'combine-single-page',
        icon: 'unfold-vertical',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['continuous-scroll', 'stitch-pages', 'custom-spacing'],
        relatedTools: ['n-up-pdf', 'merge-pdf', 'posterize-pdf'],
    },
    {
        id: 'view-metadata',
        slug: 'view-metadata',
        icon: 'info',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'json',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['view-properties', 'view-author', 'view-dates', 'view-keywords'],
        relatedTools: ['edit-metadata', 'remove-metadata', 'pdf-to-json'],
    },
    {
        id: 'edit-metadata',
        slug: 'edit-metadata',
        icon: 'file-cog',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['edit-title', 'edit-author', 'edit-subject', 'edit-keywords'],
        relatedTools: ['view-metadata', 'remove-metadata', 'bookmark'],
    },
    {
        id: 'pdf-to-zip',
        slug: 'pdf-to-zip',
        icon: 'stretch-horizontal',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'zip',
        maxFileSize: LARGE_FILE_SIZE,
        maxFiles: 100,
        features: ['package-pdfs', 'compression', 'batch-process'],
        relatedTools: ['merge-pdf', 'extract-attachments', 'split-pdf'],
    },
    {
        id: 'compare-pdfs',
        slug: 'compare-pdfs',
        icon: 'git-compare',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 2,
        features: ['side-by-side', 'highlight-differences', 'overlay-mode'],
        relatedTools: ['merge-pdf', 'view-metadata', 'edit-pdf'],
    },
    {
        id: 'posterize-pdf',
        slug: 'posterize-pdf',
        icon: 'notepad-text-dashed',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['split-large-page', 'custom-grid', 'overlap-setting'],
        relatedTools: ['n-up-pdf', 'divide-pages', 'fix-page-size'],
    },
    {
        id: 'pdf-booklet',
        slug: 'pdf-booklet',
        icon: 'book-open',
        category: 'organize-manage',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['booklet-layout', 'saddle-stitch', 'grid-modes', 'paper-sizes', 'preview'],
        relatedTools: ['n-up', 'posterize-pdf', 'print-pdf'],
    },
];
