import { Tool } from '@/types/tool';
import { DEFAULT_MAX_FILE_SIZE } from './constants';

export const securePdfTools: Tool[] = [
    {
        id: 'encrypt-pdf',
        slug: 'encrypt-pdf',
        icon: 'lock',
        category: 'secure-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['password-protection', 'aes-encryption', 'permissions'],
        relatedTools: ['decrypt-pdf', 'change-permissions', 'sanitize-pdf'],
    },
    {
        id: 'sanitize-pdf',
        slug: 'sanitize-pdf',
        icon: 'brush-cleaning',
        category: 'secure-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['remove-metadata', 'remove-annotations', 'remove-scripts', 'remove-attachments'],
        relatedTools: ['remove-metadata', 'flatten-pdf', 'find-and-redact'],
    },
    {
        id: 'find-and-redact',
        slug: 'find-and-redact',
        icon: 'search-x',
        category: 'secure-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['search-text', 'batch-redact', 'regex-search', 'selective-redact', 'preview-matches'],
        relatedTools: ['sanitize-pdf', 'edit-pdf', 'remove-metadata'],
    },
    {
        id: 'decrypt-pdf',
        slug: 'decrypt-pdf',
        icon: 'unlock',
        category: 'secure-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['remove-password', 'unlock-pdf', 'preserve-content'],
        relatedTools: ['encrypt-pdf', 'remove-restrictions', 'change-permissions'],
    },
    {
        id: 'flatten-pdf',
        slug: 'flatten-pdf',
        icon: 'layers',
        category: 'secure-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['flatten-forms', 'flatten-annotations', 'non-editable'],
        relatedTools: ['sanitize-pdf', 'remove-annotations', 'form-filler'],
    },
    {
        id: 'remove-metadata',
        slug: 'remove-metadata',
        icon: 'file-x',
        category: 'secure-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['strip-metadata', 'remove-author', 'remove-dates', 'privacy'],
        relatedTools: ['sanitize-pdf', 'edit-metadata', 'view-metadata'],
    },
    {
        id: 'change-permissions',
        slug: 'change-permissions',
        icon: 'shield-check',
        category: 'secure-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['print-permission', 'copy-permission', 'edit-permission', 'annotation-permission'],
        relatedTools: ['encrypt-pdf', 'decrypt-pdf', 'remove-restrictions'],
    },
    {
        id: 'digital-sign-pdf',
        slug: 'digital-sign-pdf',
        icon: 'file-key',
        category: 'secure-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'pdf',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 1,
        features: ['x509-certificate', 'pfx-p12-pem', 'visible-signature', 'signature-reason', 'timestamp'],
        relatedTools: ['validate-signature', 'encrypt-pdf', 'sign-pdf'],
    },
    {
        id: 'validate-signature',
        slug: 'validate-signature',
        icon: 'shield-check',
        category: 'secure-pdf',
        acceptedFormats: ['.pdf'],
        outputFormat: 'json',
        maxFileSize: DEFAULT_MAX_FILE_SIZE,
        maxFiles: 10,
        features: ['verify-signatures', 'certificate-info', 'integrity-check', 'batch-validation'],
        relatedTools: ['digital-sign-pdf', 'view-metadata', 'decrypt-pdf'],
    },
];
